version: "3.3"

services:
  database:
    container_name: polls_database
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432

volumes:
  pgdata: